# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\design\alert.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_alertWidget(object):
    def setupUi(self, alertWidget):
        alertWidget.setObjectName("alertWidget")
        alertWidget.resize(900, 450)
        alertWidget.setStyleSheet("QWidget {\n"
                                  "    background-color: #394573;\n"
                                  "    color: #fafafc;\n"
                                  "    font-family: \'SF Pro\';\n"
                                  "    font-size: 14pt;\n"
                                  "    text-align: left;\n"
                                  "    font-weight: 1000;\n"
                                  "}\n"
                                  "")
        self.pictureLabel = QtWidgets.QLabel(alertWidget)
        self.pictureLabel.setGeometry(QtCore.QRect(0, 210, 900, 271))
        self.pictureLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pictureLabel.setObjectName("pictureLabel")
        self.textLabel = QtWidgets.QLabel(alertWidget)
        self.textLabel.setGeometry(QtCore.QRect(0, 0, 900, 321))
        self.textLabel.setText("")
        self.textLabel.setPixmap(QtGui.QPixmap(".\\design\\alert.png"))
        self.textLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.textLabel.setObjectName("textLabel")

        self.retranslateUi(alertWidget)
        QtCore.QMetaObject.connectSlotsByName(alertWidget)

    def retranslateUi(self, alertWidget):
        _translate = QtCore.QCoreApplication.translate
        alertWidget.setWindowTitle(_translate("alertWidget", "Form"))
        self.pictureLabel.setText(_translate("alertWidget", "Error: the flash drive has been pulled out\n"
                                                            "To continue work, please, insert it back in"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    alertWidget = QtWidgets.QWidget()
    ui = Ui_alertWidget()
    ui.setupUi(alertWidget)
    alertWidget.show()
    sys.exit(app.exec_())
