# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\design\delete_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore
from PyQt5 import QtGui
from PyQt5 import QtWidgets


class Ui_deletePasswordDialog(object):
    def setupUi(self, deletePasswordDialog):
        deletePasswordDialog.setObjectName("deletePasswordDialog")
        deletePasswordDialog.resize(410, 260)
        deletePasswordDialog.setStyleSheet("QWidget {\n"
                                           "    background-color: #262f4d;\n"
                                           "    color: #fafafc;\n"
                                           "    font-family: \'SF Pro\';\n"
                                           "    font-size: 14pt;\n"
                                           "    font-weight: 1000;\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton {\n"
                                           "    background-color: #394573;\n"
                                           "    border: none;\n"
                                           "    border-radius: 15px;\n"
                                           "    padding: 10px 20px;\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:hover {\n"
                                           "    background-color: #4a4c54;\n"
                                           "}\n"
                                           "\n"
                                           "QLabel {\n"
                                           "    text-align: center;\n"
                                           "}")
        self.verticalLayoutWidget = QtWidgets.QWidget(deletePasswordDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 391, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sureLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.sureLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sureLabel.setObjectName("sureLabel")
        self.verticalLayout.addWidget(self.sureLabel)
        self.adminLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.adminLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.adminLabel.setObjectName("adminLabel")
        self.verticalLayout.addWidget(self.adminLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.verticalLayout.addWidget(self.passwordLineEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.errorLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.errorLabel.setText("")
        self.errorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.errorLabel.setObjectName("errorLabel")
        self.verticalLayout.addWidget(self.errorLabel)

        self.retranslateUi(deletePasswordDialog)
        self.buttonBox.accepted.connect(deletePasswordDialog.accept)  # type: ignore
        self.buttonBox.rejected.connect(deletePasswordDialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(deletePasswordDialog)

    def retranslateUi(self, deletePasswordDialog):
        _translate = QtCore.QCoreApplication.translate
        deletePasswordDialog.setWindowTitle(_translate("deletePasswordDialog", "Dialog"))
        self.sureLabel.setText(_translate("deletePasswordDialog", "Are you sure\n"
                                                                  "you want to delete password?"))
        self.adminLabel.setText(_translate("deletePasswordDialog", "Admin Password:"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    deletePasswordDialog = QtWidgets.QDialog()
    ui = Ui_deletePasswordDialog()
    ui.setupUi(deletePasswordDialog)
    deletePasswordDialog.show()
    sys.exit(app.exec_())
