# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\design\delete_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_deletePasswordDialog(object):
    def setupUi(self, deletePasswordDialog):
        deletePasswordDialog.setObjectName("deletePasswordDialog")
        deletePasswordDialog.resize(410, 260)
        deletePasswordDialog.setStyleSheet("QWidget {\n"
"    background-color: #262f4d;\n"
"    color: #fafafc;\n"
"    font-family: \'SF Pro\';\n"
"    font-size: 14pt;\n"
"    font-weight: 1000;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #394573;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4a4c54;\n"
"}\n"
"\n"
"QLabel {\n"
"    text-align: center;\n"
"}")
        self.verticalLayoutWidget = QtWidgets.QWidget(deletePasswordDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 391, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)

        self.retranslateUi(deletePasswordDialog)
        self.buttonBox.accepted.connect(deletePasswordDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(deletePasswordDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(deletePasswordDialog)

    def retranslateUi(self, deletePasswordDialog):
        _translate = QtCore.QCoreApplication.translate
        deletePasswordDialog.setWindowTitle(_translate("deletePasswordDialog", "Dialog"))
        self.label.setText(_translate("deletePasswordDialog", "Are you sure\n"
"you want to delete password?"))
        self.label_2.setText(_translate("deletePasswordDialog", "Admin Password:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    deletePasswordDialog = QtWidgets.QDialog()
    ui = Ui_deletePasswordDialog()
    ui.setupUi(deletePasswordDialog)
    deletePasswordDialog.show()
    sys.exit(app.exec_())
