# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\design\password_query.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore
from PyQt5 import QtGui
from PyQt5 import QtWidgets


class Ui_passwordQueryWidget(object):
    def setupUi(self, passwordQueryWidget):
        passwordQueryWidget.setObjectName("passwordQueryWidget")
        passwordQueryWidget.resize(710, 240)
        passwordQueryWidget.setMinimumSize(QtCore.QSize(710, 240))
        passwordQueryWidget.setMaximumSize(QtCore.QSize(710, 240))
        passwordQueryWidget.setStyleSheet("QWidget {\n"
                                          "    background-color: transparent;\n"
                                          "    color: #fafafc;\n"
                                          "    font-family: \'SF Pro\';\n"
                                          "    font-size: 14pt;\n"
                                          "    text-align: center;\n"
                                          "    font-weight: 1000;\n"
                                          "}\n"
                                          "\n"
                                          "QWidget#passwordQueryWidget {\n"
                                          "    border: 4px solid #4a4c54;\n"
                                          "    border-radius: 10px;\n"
                                          "}\n"
                                          "\n"
                                          "QPushButton {\n"
                                          "    background-color: #394573;\n"
                                          "    border: none;\n"
                                          "    border-radius: 15px;\n"
                                          "    padding: 10px 20px;\n"
                                          "    text-align: center;\n"
                                          "}\n"
                                          "\n"
                                          "QPushButton:hover {\n"
                                          "    background-color: #4a4c54;\n"
                                          "}\n"
                                          "\n"
                                          "QLineEdit {\n"
                                          "    background-color: transparent;\n"
                                          "    border: 1px solid #394573;\n"
                                          "    border-radius: 15px;\n"
                                          "    padding: 10px 5px;\n"
                                          "    padding-left: 30px;\n"
                                          "}\n"
                                          "\n"
                                          "QLabel {\n"
                                          "    background-color: transparent;\n"
                                          "    color: #fafafc;\n"
                                          "    font-family: \'SF Pro\';\n"
                                          "    font-size: 14pt;\n"
                                          "    qproperty-alignment: \'AlignCenter\';\n"
                                          "    font-weight: 500;\n"
                                          "}")
        self.gridLayoutWidget = QtWidgets.QWidget(passwordQueryWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 6, 691, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.usernameLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.usernameLineEdit.setReadOnly(True)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.gridLayout.addWidget(self.usernameLineEdit, 1, 1, 1, 1)
        self.usernameLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.usernameLabel.setObjectName("usernameLabel")
        self.gridLayout.addWidget(self.usernameLabel, 0, 1, 1, 1)
        self.domainLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.domainLineEdit.setReadOnly(True)
        self.domainLineEdit.setObjectName("domainLineEdit")
        self.gridLayout.addWidget(self.domainLineEdit, 1, 0, 1, 1)
        self.showPasswordButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.showPasswordButton.setObjectName("showPasswordButton")
        self.gridLayout.addWidget(self.showPasswordButton, 3, 1, 1, 1)
        self.adminLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.adminLabel.setObjectName("adminLabel")
        self.gridLayout.addWidget(self.adminLabel, 2, 1, 1, 1)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.passwordLineEdit.setReadOnly(True)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.gridLayout.addWidget(self.passwordLineEdit, 3, 0, 1, 1)
        self.domainLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.domainLabel.setObjectName("domainLabel")
        self.gridLayout.addWidget(self.domainLabel, 0, 0, 1, 1)
        self.passwordLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.gridLayout.addWidget(self.passwordLabel, 2, 0, 1, 1)
        self.editQueryButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.editQueryButton.setObjectName("editQueryButton")
        self.gridLayout.addWidget(self.editQueryButton, 5, 0, 1, 1)
        self.deleteQueryButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.deleteQueryButton.setObjectName("deleteQueryButton")
        self.gridLayout.addWidget(self.deleteQueryButton, 5, 1, 1, 1)

        self.retranslateUi(passwordQueryWidget)
        QtCore.QMetaObject.connectSlotsByName(passwordQueryWidget)

    def retranslateUi(self, passwordQueryWidget):
        _translate = QtCore.QCoreApplication.translate
        passwordQueryWidget.setWindowTitle(_translate("passwordQueryWidget", "Form"))
        self.usernameLabel.setText(_translate("passwordQueryWidget", "Username"))
        self.showPasswordButton.setText(_translate("passwordQueryWidget", "Show Password"))
        self.adminLabel.setText(_translate("passwordQueryWidget", "Protected With Admin Rights"))
        self.domainLabel.setText(_translate("passwordQueryWidget", "Domain"))
        self.passwordLabel.setText(_translate("passwordQueryWidget", "Password"))
        self.editQueryButton.setText(_translate("passwordQueryWidget", "Edit"))
        self.deleteQueryButton.setText(_translate("passwordQueryWidget", "Delete"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    passwordQueryWidget = QtWidgets.QWidget()
    ui = Ui_passwordQueryWidget()
    ui.setupUi(passwordQueryWidget)
    passwordQueryWidget.show()
    sys.exit(app.exec_())
